[project]
name = "mcp-servers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.128.4",
    "mcp>=1.26.0",
    "mlflow>=3.9.0",
    "requests>=2.32.5",
]
